### ISSUE TITLE
Conexión frontend app con backend

### ISSUE THREAD

**Issue by Markles01** [UNIZAR-30226-2020-07/AppMovil#6]
Adaptar las distintas funciones e implementaciones realizadas por el frontend, para poder probar las distintas funcionalidades de la interfaz, a la conexión con el backend

**Comment by aechavarris** [comment]
Reproduccion de canciones funciona, (falta arreglar seekbar), busqueda de canciones falta testearla, mostrar playlist del usuario ( no se puede testear porque falta añadir playlist), mostrar canciones de una playlist ( sin empezar), eliminar playlist y eliminar cancion de playlist, lo mismo, sin empezar.

**Comment by aechavarris** [comment]
Falta conectar amigos, cerrar sesion, cambiar usuario, cambiar e-mail
